import "./globals.css";
import type { Metadata } from "next";
import Header from "../components/Header";
import SearchSection from "@/components/SearchSection";
import Providers from "@/components/Providers";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Ecommerce-Tickets",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <section className="min-h-screen">
          <Providers>
            <Header />
            <SearchSection />
            {children}
          </Providers>
        </section>
        <section>
          <Footer />
        </section>
      </body>
    </html>
  );
}
